### ISSUE TITLE
Twitter connect doesn´t work in Domino 9.0

### ISSUE THREAD

**Issue by Lorderich** [OpenNTF/SocialSDK#1153]
Hello,

i am trying to get the SDK working with Twitter.

Everything went fine, until i am trying to authorize the app on Twitter. I get the “authorize app” screen, i provide the allowence, the Twitter site redirects to the XPagesSBT.nsf.

Using the latest version of the social enabler XPages Social Enabler Version: 901_201311181140 and the provided site.xml update site.

Here again, the website loads the Twitter Authorize screen and so on. This issue can be handled hours and hours. Every time when the Twitter Authorize screen redirects to/XPagesSBT.nsf/ i can see in the error in the console log:

[2074:000A-2100] 13.01.2014 13:50:14 HTTP JVM: CLFAD0211E: Exception thrown. F
or more detailed information, please consult error-log-0.xml located in D:/Lotus
DominoData/domino/workspace/logs
[2074:000A-2100] 13.01.2014 13:50:14 HTTP JVM: CLFAD0246E: Exception occurred
servicing request for:/development/XPagesSBT.nsf/Twitter.xsp - HTTP Code: 500.
For more detailed information, please consult error-log-0.xml located in D:/Lotu
sDominoData/domino/workspace/logs

I tried several version, all have the same issue.

Issue is also reproduceable for domino 8.5.3

**Comment by prb112** [comment]
as this involves APIs not directly owned/worked on by the team I am closing this.  It's a stretch feature.
