### ISSUE TITLE
Member objects for Community Members do not contain CommunityUUID

### ISSUE THREAD

**Issue by andylwelch** [OpenNTF/SocialSDK#1469]
The Community ID is missing from the Activity Member object

For example, the response from http://<CONNECTIONS_URL>/activities/service/atom2/forms/acl?activityUuid=<ACTIVITY_UUID> (where ACTIVITY_UUID> is substituted for the id of the Activity) contains 3 IDs;  MemberId, UserId & CommunityUUID. 

![image](https://cloud.githubusercontent.com/assets/7505965/2896815/75b724bc-d573-11e3-8d27-4c21ad50e5a9.png)

Compared to the SBT Member object which only contains 2; MemberId & UserId.

**Comment by prb112** [comment]
It's in 1.1.*
