### ISSUE TITLE
Oauth credentials are not being persisted to the configured database

### ISSUE THREAD

**Issue by seanlaval** [OpenNTF/SocialSDK#1478]
Even though a db2 database has been created using the supplied script, a datasource set up and the necessary configuration changes made in managed-beans.xml, credentials never get saved to the database so the oauth authorization must happen for each new browser session.

**Comment by prb112** [comment]
The root of the problem tracked back to incorrect tables and malformed sql.  It's no updated, and will be in the latest build.
