### ISSUE TITLE
Retrieving, creating and updating contents of a WikiPage in Connections

### ISSUE THREAD

**Issue by magnetronnie** [OpenNTF/SocialSDK#1504]
I first posted this on SO to verify this is actually a bug: http://stackoverflow.com/questions/23674389/how-to-get-and-set-contents-on-a-wikipage

For short:
WikiPage getContent() throws a ClassCastException.
WikiPage setContent() doesn't seem to do anything at all.

**Comment by prb112** [comment]
The WikiService is functioning as designed.  We will clarify the support in the next release notes.
