### ISSUE TITLE
adding comments to ActivityNode

### ISSUE THREAD

**Issue by pavoldobias** [OpenNTF/SocialSDK#1537]
Hi,
please would be possible to enhance ActivityNode service for adding comments under ActivityNode ?

![image](https://cloud.githubusercontent.com/assets/7713009/3090972/cd2891d2-e594-11e3-820f-efd4cd442fb1.png)

Thanks

**Comment by prb112** [comment]
There is an existing InReplyTo object in the ActivityNode.  The InReplyTo provides the link to the comment feature you ask for.
