### ISSUE TITLE
ActivityStream javascript extension properties

### ISSUE THREAD

**Issue by weihangChen** [OpenNTF/SocialSDK#1547]
the example code on 
https://greenhouse.lotus.com/sbt/SBTPlayground.nsf/JavaScriptSnippets.xsp#snippet=Social_ActivityStreams_Controls_Simple_Stream_All_Extensions

does not really work, I can see all extensions UI being displayed, but three of four configured extensions(save/commenting/delete) do not work

can see errors on all three of them on developer tools

**Comment by prb112** [comment]
The Dojo layers changed from version IBM Connections 4.5 to 5.0.  No plans to fix
