### ISSUE TITLE
Need method to get all invitations for a community

### ISSUE THREAD

**Issue by sjleis** [OpenNTF/SocialSDK#1549]
Viewing community invitations in the Connections UI, there's a "Feed for Invitations" link that gets all invitations for a single community.
It uses a path like /communities/service/atom/community/invites?communityUuid=[communityUuid]

Please add a method to CommunityService and/or Community in the SBT API to retrieve this feed as an InviteList.

**Comment by prb112** [comment]
added to the 1.1.11 release (not same implementation)
