### ISSUE TITLE
IBM SBT SDK: Represent Community Widgets as Java objects

### ISSUE THREAD

**Issue by zipwiz** [OpenNTF/SocialSDK#1569]
I cannot find any representation (as a Java class) of Community Widgets as general objects.

There should be added support ("someone should implement...") for Community Widgets management to the IBM SBT SDK for Java, like there is support for other entities like Communities, Forums, Blogs...

Starting from "community.getWidgets()", a general Widget type would be required. Depending on the actual widgetDefId, a collection of entries of that type should be available, like "Forums", "Files" etc.

The operations described at http://www-10.lotus.com/ldd/appdevwiki.nsf/xpDocViewer.xsp?lookupName=IBM+Connections+4.5+API+Documentation#action=openDocument&res_title=Community_widgets_feed_ic45&content=pdcontent should be available in a reasonable way, i. e. things like "community.addWidget(widgetDefId)", "community.getWidget(widgetInstanceId)", "community.getWidgets(widgetDefId, ...)", "community.hideWidget(widgetInstanceId)" etc. should be implemented.

**Comment by zipwiz** [comment]
is related to #1623 (if this is still true)

**Comment by zipwiz** [comment]
addressed but not completely resolved by #1647 with 44dfa75 . Further enhancements welcome.

**Comment by prb112** [comment]
Per May14 comment - closing down issue - reopen specifics thanks Paul
