### ISSUE TITLE
Suggestion: ProfileService.checkColleague should catch 404 error and return null

### ISSUE THREAD

**Issue by sjleis** [OpenNTF/SocialSDK#1579]
In the Java class com.ibm.sbt.services.client.connections.profiles.ProfileService, these two methods can be used to check if two people are colleagues:
- checkColleague(String,String); and
- checkColleague(String,String,Map<String,String>).

These use the Connections API for checking whether two people are colleagues.
According to the API document, and confirmed by my testing, this API request produces a 404 error when the specified people are not colleagues and have no pending invitation.

The SBT methods throw an exception when the 404 error occurs. As this particular 404 error is expected behaviour, the SBT methods should catch it and, instead of re-throwing it to the caller, just return null to indicate that the specified people are not colleagues.

**Comment by prb112** [comment]
Fix will be in the next build. changes were required to a lowerlevel code to allow 404 through a checkStatus.   I changed that and committed the code.  a few other items of code were changed related to 
Failed tests:   testGetCommunityByInvalidId(com.ibm.sbt.services.client.connections.communities.CommunityServiceNoCommonCommunityTest): Expected exception: com.ibm.sbt.services.client.ClientServicesException
  deleteWikiTest(com.ibm.sbt.services.client.connections.wikis.WikiCreateAndDeleteTest): Expected test to throw (an instance of com.ibm.sbt.services.client.ClientServicesException and exception with message a string containing "404:Not Found")
  getAndDeleteWikiPageTest(com.ibm.sbt.services.client.connections.wikis.WikiPageTest): Expected test to throw (an instance of com.ibm.sbt.services.client.ClientServicesException and exception with message a string containing "404:Not Found")
  getAndDeleteWikiPageTest(com.ibm.sbt.services.client.connections.wikis.WikiPageTest): Expected test to throw (an instance of com.ibm.sbt.services.client.ClientServicesException and exception with message a string containing "404:Not Found")
