### ISSUE TITLE
OAuth2Handler bug with getAccessTokenForAuthorizedUsingPOST & double encoding

### ISSUE THREAD

**Issue by MartinRolph** [OpenNTF/SocialSDK#1597]
com.ibm.sbt.security.authentication.oauth.consumer.OAuth2Handler 
getAccessTokenForAuthorizedUsingPOST

lines 272-276
the BasicNameValuePair values do not need to be encoded as the whole entity is encoded afterwards in this line
UrlEncodedFormEntity sendentity = new UrlEncodedFormEntity(parameters, HTTP.UTF_8);

e.g. change
'parameters.add(new BasicNameValuePair(Configuration.OAUTH2_CALLBACK_URI, URLEncoder.encode(client_uri, "UTF-8")));   '
to
'parameters.add(new BasicNameValuePair(Configuration.OAUTH2_CALLBACK_URI, client_uri));   '

**Comment by prb112** [comment]
Fixed in latest build
