### ISSUE TITLE
com.ibm.sbt.security.authentication.oauth.consumer.OAuth2Handler  Redirect_Uri rather than Callback_uri

### ISSUE THREAD

**Issue by MartinRolph** [OpenNTF/SocialSDK#1598]
re: com.ibm.sbt.security.authentication.oauth.consumer.OAuth2Handler 

IMO the various getAccessToken methods should use REDIRECT_URI rather than CALLBACK_URI as this is truer to the OAuth2 standard.

e.g.
change
url.append(Configuration.OAUTH2_CALLBACK_URI).append('=').append(URLEncoder.encode(client_uri, "UTF-8"));
			
to
url.append(Configuration.OAUTH2_REDIRECT_URI).append('=').append(URLEncoder.encode(client_uri, "UTF-8"));
			
However I guess that would break the subclasses! So perhaps need a property which could be override in a subclass to specify the param name of the redirect value.

**Comment by prb112** [comment]
This feature is working as designed. Sedar is correct that is the way to extend it.
