### ISSUE TITLE
ActivityService.getActivityNode(String activityNodeId) does not work correctly

### ISSUE THREAD

**Issue by ShirouWrath** [OpenNTF/SocialSDK#1607]
Method returns ActivityNode object but without data of assigned persion.
I use XPages application for development + SBT through JSSS.

Tested on:
IBM Connections: v5 (corporate) and Greenhouse,
IBM SBT SDK: 1.0.3.20140723-1200,
Execution context: Domino Release 9.0.1HF25

**Comment by ToanNM-CCRC** [comment]
Hi team
I have the same issue with due date field. Although I use setDueDate method, the due date field is still empty.
Any help will be appreciated too :)

**Comment by prb112** [comment]
There were changes to the ActivityNode Todo/Assign recently.  I suggest you use the raw API in the interim.

**Comment by ToanNM-CCRC** [comment]
Hi prb112
thanks for your response. I am not familiar with PAI world. What is raw API ?
