### ISSUE TITLE
getSummary from wiki service retrieves null

### ISSUE THREAD

**Issue by sergiovergara** [OpenNTF/SocialSDK#1619]
Trying to get the content of the page, the result is null when wikipage.getSummary():

![untitled](https://cloud.githubusercontent.com/assets/8028637/4334973/76fd612c-3ff6-11e4-8f08-a587db129163.png)

![capture](https://cloud.githubusercontent.com/assets/8028637/4334976/8638ed64-3ff6-11e4-96f4-3ca9d730994d.PNG)

Could you check it please?

**Comment by Thorien** [comment]
Hello, is the function for getting content already implemented in the JS ? I see this as pretty useful function.

**Comment by fmoloney** [comment]
The JavaScript sdk doesn't have support for getting the content of the page, in the Java it just downloads the page and returns the content. You could maybe do something similar in JavaScript if it was necessary but there are no plans to add it atm.

https://github.com/OpenNTF/SocialSDK/blob/master/sdk/com.ibm.sbt.core/src/main/java/com/ibm/sbt/services/client/connections/wikis/WikiPage.java#L94
