### ISSUE TITLE
WikiService using OAuth 

### ISSUE THREAD

**Issue by nbezembinder1** [OpenNTF/SocialSDK#1628]
Using the latest Social Business Toolkit SDK release ```(sbtsdk-1.0.3.20140723-1200)``` I am unable to use the ```WikiService``` class in ```com.ibm.sbt.services.client.connections.wikis```, in particular, retrieving wiki's using ```getMyWikis(null)```.

I'm using a custom SmartCloudOAuthEndpoint on a Connections Cloud environment (https://apps.ce.collabserv.com). 

```
WikiService ws = new WikiService(oauthEndpoint);
EntityList<Wiki> wikis = ws.getMyWikis(null);
```

Java then returns an ``` java.lang.ClassCastException: org.apache.http.conn.EofSensorInputStream incompatible with org.w3c.dom.Document```

Using [Fiddler Web Debugger](http://www.telerik.com/fiddler) I can see a request being made to ```/wikis/oauth/api/mywikis/feed``` but it does not return a XML feed, instead it tries to return the login page.

![image](https://cloud.githubusercontent.com/assets/9671599/4989901/04af98d4-6980-11e4-9b68-7e16b54bc282.png)

If I try to use CommunityService in ```com.ibm.sbt.services.client.connections.communities```

```
CommunityService cs = new CommunityService(oauthEndpoint);
CommunityList myCommunities = cs.getMyCommunities();
```

It returns a list of my communities. 

![image](https://cloud.githubusercontent.com/assets/9671599/4989960/20ff5bc2-6981-11e4-8506-2e6c84a90b91.png)

If I use ```ws.getMyWikis(null);``` and authenticate using BasicAuthentication it does return a list my of my wiki's. 

Could anybody take a look?

**Comment by prb112** [comment]
This issue should be resolved, I have had the oauth pattern updated on Collabserv, so that it is enabled.
