### ISSUE TITLE
Adding tags to a file incorrectly adds a "tag_word" tag in addition to my tags

### ISSUE THREAD

**Issue by sjleis** [OpenNTF/SocialSDK#1636]
When I add tags to a `File` object, then update the file using `FileService.updateCommunityFileMetadata`, the file in Connections ends up with the tags I added along with a tag called "tag_word".
I'm assuming, but haven't checked, that the same happens with files outside communities.

This is caused by the following code in `FileSerializer.getFileEntry()`:
```
if (entity.getTags()!=null)
	for (String tag : entity.getTags()) {
		appendChildren(n, textElement(CATEGORY, tag,                
			attribute(TERM, CATEGORY_TAG)
		));
	}
```
The `CATEGORY_TAG` constant has the value "tag_word", which is the incorrectly added tag.

I think this comes from a misunderstanding of the Connections API documentation. The documentation says this represents a tag on a file:
```
	<category term="tag_word"/>
```

I think the intention is that "tag_word" is a placeholder, which the caller should replace with an actual tag in the `term` attribute, and the element shouldn't have any content.

What the current code does is send "tag_word" as the term attribute of every tag, with the real tag as content of the element. This has the effect of adding both the element content and "tag_word" as tags.

**Comment by prb112** [comment]
which version of the toolkit are you using?  are you using 1.1.3 or higher? I didn't get this from the fileserializer tests I added

**Comment by prb112** [comment]
I believe this is previously fixed. If not, Scott, please let us know.
