### ISSUE TITLE
isExternal is missing from Community Object (Java)

### ISSUE THREAD

**Issue by MartinRolph** [OpenNTF/SocialSDK#1637]
The Connections atom feed for a community contains this..

<snx:isExternal>true</snx:isExternal>

indicating if it's available to external users.

This value isn't available from the Community object

**Comment by DaviRyan** [comment]
@MartinRolph It would be great if you could add this to the CommunityService class, you would simply add a method called isExternalCommunity and that method would contain this.getAsString(./snx:isExternal), You can take a look at how the rest of the properties are retrieved and match the pattern. This is an open source project and would be great if users can contribute.

**Comment by prb112** [comment]
added to Community object, will be in next release
