### ISSUE TITLE
Please remove extra functions added to i18n bridge

### ISSUE THREAD

**Issue by ddumontatibm** [OpenNTF/SocialSDK#1662]
https://github.com/OpenNTF/SocialSDK/blob/master/sdk/com.ibm.sbt.web/src/main/webapp/js/sdk/sbt/i18n.js

This function has extra code monkey-patched on to the i18n plugin bridge
https://github.com/OpenNTF/SocialSDK/blob/master/sdk/com.ibm.sbt.web/src/main/webapp/js/sdk/_bridges/dojo/i18n.js

Which has a dependency on dojo/date/locale. (why aren't these AMD dependencies?????)

We would like to use a loader alias to replace the sbt/i18n with dojo's i18n module, but code in sbt already makes use of these functions (which really should be in another module)

The reason is that this practice is causing unnecessary extra code requests when using the JavascriptAggregator because the the i18n plugin ends up having dependencies on modules we do not want to load with the base layer, and using dependencies we cannot discover through normal AMD declarations.  It would be ideal to move the functionality that you are adding to the i18n bridge plugin to a new bridge module and fix any references to it.

**Comment by markewallace** [comment]
@prb112 I have assigned this one to David and the plan is to get this resolved this week

**Comment by DaviRyan** [comment]
Code to fix this issue has been merged.
