### ISSUE TITLE
Trying to use communityService.getCommunityEvents(communityId, startDate.toUTCString());

### ISSUE THREAD

**Issue by StevenRieger** [OpenNTF/SocialSDK#1663]
I found a great snippet on the playground that works great on the playground however, when I run it in my xPage I get the following :(  I am running on prem connections 4.5 and I have several other scripts from the playground that run great.  

Thoughts?

2/27/15 3:02 PM: Exception Thrown                                       
Context Path: /dblms/lmsIntraNet.nsf                                    
Page Name: /xpMain.xsp                                                  
Control id: dataView2                                                   
Property: value                                                         
Script interpreter error, line=6, col=119: Unknown member               
'getCommunityEvents' in Java class 'com.ibm.sbt.services.client.        
connections.communities.CommunityService'                               
     4: startDate.setFullYear(2012,01,01);                   
     5: var events = communityService.getCommunityEvents(    
communityId, startDate.toUTCString());                                  
->   6: return events;                                       
com.ibm.xsp.exception.EvaluationExceptionEx: Error while executing      
JavaScript computed expression                                          
at com.ibm.xsp.binding.javascript.JavaScriptValueBinding.getValue      
(JavaScriptValueBinding.java:132)                                       
at com.ibm.xsp.component.UIDataIterator.getValue(UIDataIterator.java:  
422)                                                                    
at com.ibm.xsp.component.UIDataIterator.createDataModel(UIDataIterator.
java:206)                                                               
at com.ibm.xsp.component.UIDataIterator.getDataModel(UIDataIterator.   
java:160)                                                               
at com.ibm.xsp.extlib.renderkit.html_extended.data.                    
AbstractDataViewRenderer.initViewDefinition(AbstractDataViewRenderer.   
java:241)                                                               
at com.ibm.xsp.extlib.renderkit.html_extended.data.DataViewRenderer.   
initViewDefinition(DataViewRenderer.java:88)                            
at com.ibm.xsp.extlib.renderkit.html_extended.data.                    
AbstractDataViewRenderer.writeMainContainer(AbstractDataViewRenderer.   
java:698)                                                               
at com.ibm.xsp.extlib.renderkit.html_extended.data.                    
AbstractDataViewRenderer.encodeBegin(AbstractDataViewRenderer.java:144) 
at com.ibm.xsp.renderkit.ReadOnlyAdapterRenderer.encodeBegin           
(ReadOnlyAdapterRenderer.java:146)                                      
at javax.faces.component.UIComponentBase.encodeBegin(UIComponentBase.  
java:956)                                                               
......

**Comment by prb112** [comment]
please post a log from the IBM_Technical_Support folder on your domino server (of course focused on your xpages issue) also any traces you have

**Comment by StevenRieger** [comment]
The messages above are from the xPages error log.  The only thing that shows up in the console log is an exception occurred please view the log error.....

**Comment by StevenRieger** [comment]
This is the snippet from the playground:
require(["sbt/connections/CommunityService", "sbt/dom"], 
    function(CommunityService, dom) {
	    var createRow = function(event) {
	        var table = dom.byId("eventsTable");
	        var tr = document.createElement("tr");
	        table.appendChild(tr);
	        var td = document.createElement("td");
	        td.appendChild(dom.createTextNode(event.getTitle()));
	        tr.appendChild(td);
	        td = document.createElement("td");
	        td.appendChild(dom.createTextNode(event.getEventUuid()));
	        tr.appendChild(td);
	    };
    
	    var communityId = "%{name=CommunityService.communityUuid|label=communityId|helpSnippetId=Social_Communities_Get_My_Communities}";
	    var startDate = new Date();
	    startDate.setFullYear(2012,01,01);
	    
	    var communityService = new CommunityService();
	    var promise = communityService.getCommunityEvents("39a2302a-f07f-425d-bfcb-54f1b9564268", startDate.toUTCString());
	    promise.then(
	        function(events) {
	            if( events.length === 0) {
	                dom.setText("content", "There are no events scheduled after: "+startDate);
	            }
	            for (var i=0; i < events.length; i++) {
	                createRow(events[i]);
	            }
	        },
	        function(error) {
	            dom.setText("json", json.jsonBeanStringify(error));
	        }
	    );
    }
);

This is my code:
<xe:dataView id="dataView2" var="event" rows="5"
	columnTitles="true" styleClass="eventsDataView">
	<xe:this.extraColumns>
		<xe:viewExtraColumn columnTitle="Content">
		</xe:viewExtraColumn>
	</xe:this.extraColumns>
	<xe:this.summaryColumn>
		<xe:viewSummaryColumn columnTitle="Topic">
		</xe:viewSummaryColumn>
	</xe:this.summaryColumn>
	<xp:this.value>
			<![CDATA[#{javascript:
					var communityService = new com.ibm.sbt.services.client.connections.communities.CommunityService("connectionsSSO");
					var communityId = "39a2302a-f07f-425d-bfcb-54f1b9564268";
					var startDate = new Date();
					startDate.setFullYear(2012,01,01);
					var events = communityService.getCommunityEvents( communityId, startDate.toUTCString());
					return events;
				}]]>
	</xp:this.value>

**Comment by StevenRieger** [comment]
I am not using the require statement in my code.  I include the com.ibm.xsp.sbtsdk.library
If I need to use the require statement, I can't figure out how to get that to work perhaps you can help?

**Comment by StevenRieger** [comment]
OK, I've made some progress on this.  Is it possible the getCommunityEvents is a client side method of the sbt/sdk library for which I am not using.  Is it possible the com.ibm.xsp.sbtsdk.library doesn't have that method?  If not what is the best work around?

**Comment by prb112** [comment]
yes, it does not exist in the java code, which are part of the xpage code above, Sedar answered the question on StackOverflow

**Comment by StevenRieger** [comment]
Do you know if / when the getCommunityEvents will be added to the java library?

**Comment by prb112** [comment]
it'll sit in our backlog and be evaluated along with our iteration plan

**Comment by prb112** [comment]
refer to https://github.com/OpenNTF/SocialSDK/issues/1663
