### ISSUE TITLE
isFulfilled and isResolved methods in sbt/Promise with unexpected behavior

### ISSUE THREAD

**Issue by mduarte** [OpenNTF/SocialSDK#1667]
The methods *isFulfilled* and *isResolved* in the implementation of Pomises in sbt ( sdk/com.ibm.sbt.web/src/main/webapp/js/sdk/sbt/Promise.js ) has a behavior inconsistent with its comments. The comments seem to be what one would expect in the implementation (which would be the same behavior as dojo promises), however the behavior does not reflect that.

**Comment by prb112** [comment]
@mduarte we will look at it in a future iteration

**Comment by prb112** [comment]
Updated comments to match the intent of the Promise.js
