### ISSUE TITLE
Blog posts get comments does not work for on-prem Connections

### ISSUE THREAD

**Issue by stgeorgecarey** [OpenNTF/SocialSDK#1670]
The issue is:
EntityList<BlogPost> posts = service.getBlogPosts(blogHandle);
			for (BlogPost post : posts) {					
				if (post.getCommentCount() > 0) {
					EntityList<Comment> pcs = post.getComments();
the post.getComments() does not work I get an illegalArgs exception. due to this method in BlogService:

public EntityList<Comment> getEntryComments(String blogHandle, String entryAnchor, Map<String, String> parameters) throws ClientServicesException {
		String url = BlogUrls.BLOG_ENTRYCOMMENTS.format(this, BlogUrlParts.blogHandle.get(defaultHomepageHandle));

IT SHOULD BE:
public EntityList<Comment> getEntryComments(String blogHandle, String entryAnchor, Map<String, String> parameters) throws ClientServicesException {
		String url = BlogUrls.BLOG_ENTRYCOMMENTS.format(this, BlogUrlParts.blogHandle.get(blogHandle), BlogUrlParts.entryAnchor.get(entryAnchor));
		return getCommentEntityList(url, parameters);
	}
		return getCommentEntityList(url, parameters);
	}

**Comment by prb112** [comment]
you can make the contribution, and we'll happily review it, and based on tests accept it.

**Comment by stgeorgecarey** [comment]
Okay sure, but what is the process can I check it out from gitHub?

**Comment by prb112** [comment]
You'll want to fork the SocialSDK repository, and then clone the repository in your development environment, and then commit from your development environment, and open a Pull Request on this repository (from your repository).  @ManishKataria  and @projsaha  and I will look at your pull request

**Comment by prb112** [comment]
fixed in latest build - to be released soon
