### ISSUE TITLE
bss.provisioning.sample.app 0.0.1 refers to SBT 1.1.3-20150220 instead of 1.1.4-SNAPSHOT

### ISSUE THREAD

**Issue by zipwiz** [OpenNTF/SocialSDK#1671]
bss.provisioning.sample.app 0.0.1 refers to SBT 1.1.3-20150220 instead of 1.1.4-SNAPSHOT.

pom.xml should eventually fixed.

**Comment by prb112** [comment]
it should have been tagged with Latest.  I will fix and merge in.

**Comment by prb112** [comment]
I'm not sure why you are getting an old pom.xml version.  I had previous changed this to:
 <dependency>
<groupId>com.ibm.sbt</groupId>
<artifactId>com.ibm.sbt.core</artifactId>
<version>LATEST</version>
</dependency>
<dependency>

it should always compile

**Comment by prb112** [comment]
leaving open for your comment - not meant to close

**Comment by zipwiz** [comment]
I did not look into the pom.xml really I have to admit -- I simply fetched the latest commits and executed mvn clean install -fn to force a complete build. Watching the mvn output I saw that the mentioned version was downloaded. Maybe the problem has another reason.

**Comment by prb112** [comment]
I imagine it does.  I have built the source multiple times, and not hit the same issue.

**Comment by zipwiz** [comment]
I suspect that LATEST will fetch the "latest stable published build" which is currently still 1.1.3-20150220 and not 1.1.4-SNAPSHOT. Other pom's use 1.1.4-SNAPSHOT or inherited version therefore. Maybe worthwile to think about using 1.1.4-SNAPSHOT explicitly instead of generic LATEST -- however this requires active updates to all pom's when stepping forward to the next SNAPSHOT version.

**Comment by zipwiz** [comment]
According to #1676 this may be with intent also. Thus I close this now.

**Comment by prb112** [comment]
I hit the issue when running the full build, install and deploy.  I've fixed the POM for bss
