### ISSUE TITLE
Class SmartCloudFormEndpoint is referenced but not present in the codebase

### ISSUE THREAD

**Issue by zipwiz** [OpenNTF/SocialSDK#1672]
com.ibm.sbt.services.SmartCloudFormEndpoint is used in several classes, but cannot be found in the current codebase (1.1.4-SNAPSHOT as of today).

References:
* samples/domino/com.ibm.xsp.sbtsdk.playground.sbt: com.ibm.xsp.sbtsdk.playground.sbt.extensions.SbtEndpoints
* sdk/com.ibm.sbt.core: com.ibm.sbt.services.client.smartcloud.SmartCloudService

In sdk/com.ibm.sdk.core this is extremely bad since this core lib is not compileable currently.

It looks like this is an old class since it was present in 1.0.0-20140318-1817.

**Comment by prb112** [comment]
I will merge in the Fix for this issue.  The class will not return.

**Comment by prb112** [comment]
https://github.com/OpenNTF/SocialSDK/pull/1673  removes references to these classes.  
it'll be validated and a new release created soon
