### ISSUE TITLE
SearchUrls.MYSEARCH ends with slash but shouldn't

### ISSUE THREAD

**Issue by zipwiz** [OpenNTF/SocialSDK#1677]
https://github.com/OpenNTF/SocialSDK/blob/master/sdk/com.ibm.sbt.core/src/main/java/com/ibm/sbt/services/client/connections/search/SearchUrls.java : MYSEARCH ends with / but it should simply look like `{search}/atom/mysearch?{query}`.

Anyway this looks dangerous to me: Empty query Strings will always cause "?query=..." in the URL, that is: casue an explicit but empty URL parameter. Is that required?

**Comment by zipwiz** [comment]
Not yet fixed for 1.1.4-20150504-1700.

**Comment by prb112** [comment]
I did not merge in your code. It hasn't been fully reviewed.
