### ISSUE TITLE
com.ibm.sbt.web - Version in Manifest.MF

### ISSUE THREAD

**Issue by guedeWebGate** [OpenNTF/SocialSDK#1689]
During the automated build, is the version of the Manifest.MF not updated (still 1.1.6.qualifier). This lead to a conflict when the Domino Designer imports the plugin.

I think the manifest.mf can be patched, during the jar building

**Comment by prb112** [comment]
please add a screenshot, and file path for the file

**Comment by prb112** [comment]
All build artifacts are updated with 1.1.11.qualifier.  going forward it'll be up to date.
