### ISSUE TITLE
Upload new version of community file does not work

### ISSUE THREAD

**Issue by klaashoekstra** [OpenNTF/SocialSDK#1702]
This is my fix
in com.ibm.sbt.services.client.connections.files.FileUrls
change line : 
UPLOAD_NEW_VERSION_COMMUNITY_FILE(new VersionedUrl(v4_0, 	"{files}/{authType}/{accessType}/library/{communityId}/document/{fileId}/entry")),
to 
UPLOAD_NEW_VERSION_COMMUNITY_FILE(new VersionedUrl(v4_0, 	"{files}/{authType}/{accessType}/communitylibrary/{communityId}/document/{fileId}/entry")),

**Comment by prb112** [comment]
fixed in latest build - 1.1.11
