### ISSUE TITLE
Maven repo not up-to-date?

### ISSUE THREAD

**Issue by priand** [OpenNTF/SocialSDK#1705]
Looks like the latest release is 1.1.6 while maven only provides 1.1.5: http://mvnrepository.com/artifact/com.ibm.sbt

**Comment by prb112** [comment]
http://search.maven.org/#search|ga|1|com.ibm.sbt  up to date when I look at maven central

**Comment by priand** [comment]
Great - That wasn't the case 2 days ago and the maven repo has bee updated on the 21th, right after I posted this :-)
I'll use this one now. Thanks Paul!
