### ISSUE TITLE
create forum topics and replies on behalf of another user

### ISSUE THREAD

**Issue by MJonker** [OpenNTF/SocialSDK#1720]
In IBM Connections, we need to post topics and reply from a java (not web) application. I noticed in the API Documentation that you can provide a HTTP HEADER value to post a topic or reply on behalf of another user (impersonation).

We would like to use the Social Business Toolkit for this purpose, but the question is, **how** ?

I could not find a reference to *X-LConn-RunAs* in SBT source code.
Preferable it should be enough to be administrator of the forum when using this function.

Source:

http://stackoverflow.com/questions/32695692/is-x-lconn-runas-exposed-through-the-social-business-toolkit

**Comment by prb112** [comment]
We will evaluate this request in our iteration plans.

**Comment by zipwiz** [comment]
Very interesting topic. Google returns matches for X-LConn-RunAs only for Connections 5 Blogs and Forum API only. Usually forwardable LTPA tokens may also enable useful things, but if you have no "current authenticated user who is also known to Connections" this is no option anyway.

**Comment by prb112** [comment]
I've added support for a more general method to add global headers to the endpoint.
Endpoint.addHeader(Name,Value)
When X-LConn-RunAs is public, you'll update each call with the text header.
