### ISSUE TITLE
Sametime client with HTTPS

### ISSUE THREAD

**Issue by cifra2** [OpenNTF/SocialSDK#1732]
There should be HTTPS detection (in an EndPoint ?) on SocialSDK for Domino Xpages to use proper protocol and port for including Sametime resources from Sametime Proxy Server.

If you are using Sametime Client in current version SocialSDK on https pages, there are warnings about mixed content on a page...

**Comment by prb112** [comment]
is your endpoint specified with https?

**Comment by cifra2** [comment]
Actually, it's not a problem with specifying endpoint with https. It's about specifying http endpoint and then switching your pages from http to https and vice versa. For example: normal pages (http) and secure part of pages (https). it would be nice to have a configuration at an endpoint part to be able to enter https and http host/port/url. Yes, I can do workaround to have two endpoints and compute them on properties at sametime client custom component. But it would be nice to have it "blackboxed" in the library. I did it myself by overriding relevant classes:

endpoint part:
```java

package mybeans.sbt.services.endpoints;
public class SametimeSSOEndpoint extends SSOEndpoint {

	private String urls;
	
	public String getUrls() {
		return urls;
	}

	public void setUrls(String urls) {
		this.urls = urls;
	}

	@Override
	public String getUrl() {
		XSPContext context = XSPContext.getXSPContext(FacesContext.getCurrentInstance());
		XSPUrl XUrl = context.getUrl();
		if (!XUrl.getScheme().equalsIgnoreCase("http"))
			return getUrls();
		return super.getUrl();
		
	}
	@Override
	public String getUserIdentity() throws ClientServicesException {
		Context context = Context.getUnchecked();
		if (context != null) { 
			return context.getCurrentUserId();
		}
		return null;
	}

    @Override
    public String getPlatform() {
    	return PLATFORM_SAMETIME;
    }

    @Override
	public ClientService getClientService() throws ClientServicesException {
    	return new SametimeService(this);
    }
}
```

faces-config:

```xml
<managed-bean>
    <managed-bean-name>MySametime</managed-bean-name>
    <managed-bean-class>mybeans.sbt.services.endpoints.SametimeSSOEndpoint</managed-bean-class>
    <managed-bean-scope>session</managed-bean-scope>
    <managed-property>
      <property-name>url</property-name>
      <value>http://stproxy.local:9081</value>
    </managed-property>
    <managed-property>
      <property-name>urls</property-name>
      <value>https://stproxy.local:9444</value>
    </managed-property>
  </managed-bean>
```

**Comment by prb112** [comment]
The best practice with mixed content is to leave the http/https content in place. you'll note that Paul Irish's blog post on relative URLs has revisited the pattern and found wanting - http://www.paulirish.com/2010/the-protocol-relative-url/.  I recommend you extend SSOEndpoint and implement the mixed content there, we are not going to implement the endpoint you suggest.

**Comment by cifra2** [comment]
The best practice it is. But only if you are using default ports.
ok. Will implement it in my library...
