### ISSUE TITLE
Create and delete a standalone Bookmark

### ISSUE THREAD

**Issue by SiriSch** [OpenNTF/SocialSDK#1733]
Hey Paul,

I cannot find any method to create and delete a standalone bookmark.

Could you give me an example for creating a bookmark and deleting a bookmark?

Best regards,

Sirius S.

**Comment by prb112** [comment]
As you will notice in the Java code - https://github.com/OpenNTF/SocialSDK/blob/master/sdk/com.ibm.sbt.core/srcmain/java/com/ibm/sbt/services/client/connections/bookmarks/BookmarkService.java we do not support creating/delete bookmarks.  I suggest you refer to http://www-10.lotus.com/ldd/lcwiki.nsf/xpAPIViewer.xsp?lookupName=IBM+Connections+5.0+API+Documentation#action=openDocument&res_title=Working_with_bookmarks_programmatically_ic50&content=apicontent which describes the REST API
